/* Waypoint exercise library, session templates and guides. */
'use strict';

/* joints: stress each movement places on back / hip / knee / shoulder, 0 = none, 1 = some, 2 = high.
   lvl: lowest back-readiness level (1-4) at which the movement is programmed.
   type: reps | hold | carry | time. uni: counted per side. */
const EX = [
  /* ---------- Core: McGill Big 3 and friends ---------- */
  { id: 'curlup', name: 'McGill curl-up', cat: 'Core', eq: ['mat'], type: 'hold', uni: false, joints: { back: 0, hip: 0, knee: 0, shoulder: 0 }, lvl: 1,
    why: 'Trains the front core to hold the spine still without bending it. Part of the McGill Big 3.',
    setup: 'Lie on your back. Bend one knee with the foot flat; keep the other leg straight. Slide both hands, palms down, under the arch of your low back.',
    steps: ['Brace lightly, about 20% effort, as if about to be poked in the belly.', 'Lift head and shoulders just off the floor as one unit. Think "lift the chest," not "curl the neck."', 'Hold about 10 seconds while breathing normally.', 'Lower slowly. Switch the bent leg halfway through your sets.'],
    cues: ['Chin stays tucked, as if holding an egg under it', 'Low back keeps its arch on your hands', 'Only a small lift: an inch or two'],
    faults: ['Flattening the low back into the floor', 'Cranking the neck forward', 'Holding the breath'],
    jointNote: 'Back: the hands under the low back keep its natural curve, so the abs work without repeated spine bending. Replace crunches and sit-ups with this.',
    fig: { frames: [{ t: -90, tn: 90, sn: 90, tf: 135, sf: 45, fF: 90, an: 110, fn: 70, af: 110, ff: 70 }, { t: -99, h: -8, tn: 90, sn: 90, tf: 135, sf: 45, fF: 90, an: 110, fn: 70, af: 110, ff: 70 }], hold: [700, 1600], anchor: 'hip' } },
  { id: 'sideplank_knee', name: 'Side plank from knees', cat: 'Core', eq: ['mat'], type: 'hold', uni: true, joints: { back: 0, hip: 1, knee: 0, shoulder: 1 }, lvl: 1, next: 'sideplank',
    why: 'Builds the side-core muscles (obliques, quadratus lumborum) that keep the spine from buckling sideways. Big 3, easier version.',
    setup: 'Lie on your side, propped on your forearm with the elbow right under the shoulder. Bend the knees about 90 degrees.',
    steps: ['Brace lightly.', 'Push the hips up and forward until knees, hips and shoulders form a straight line.', 'Hold about 10 seconds, breathing.', 'Lower under control. Do the same holds on the other side.'],
    cues: ['Elbow under shoulder', 'Hips forward, not piked back', 'Top hand on the opposite shoulder'],
    faults: ['Hips sagging', 'Shrugging into the support shoulder', 'Rolling forward or back'],
    jointNote: 'Shoulder: keep the support shoulder pushed away from the ear. If it aches, work from a wall-lean side plank first.',
    fig: { frames: [{ t: -95, tn: 95, sn: 150, tf: 95, sf: 150, an: 0, fn: -80, af: 170, ff: 20, anchor: 'kneeN' }, { t: -112, tn: 68, sn: 150, tf: 68, sf: 150, an: 0, fn: -80, af: 170, ff: 20, anchor: 'kneeN' }], hold: [700, 1700] } },
  { id: 'sideplank', name: 'Side plank', cat: 'Core', eq: ['mat'], type: 'hold', uni: true, joints: { back: 0, hip: 1, knee: 0, shoulder: 1 }, lvl: 2, prev: 'sideplank_knee',
    why: 'Full side plank from the feet. Big 3. Side-core endurance protects the back during carrying, hiking and running.',
    setup: 'Lie on your side on your forearm, elbow under shoulder, legs straight with the top foot in front of the bottom foot.',
    steps: ['Brace lightly.', 'Lift the hips so the body is straight from head to feet.', 'Hold about 10 seconds, breathing.', 'Lower. Hold for the same reps on the other side.'],
    cues: ['Straight line ear to ankle', 'Top foot in front for stability', 'Squeeze the glutes'],
    faults: ['Hips sagging or piking', 'Head drooping', 'Shoulder crunched toward the ear'],
    jointNote: 'Hips: glute squeeze keeps the hip joint centered. Shoulder: stack elbow under shoulder.',
    fig: { frames: [{ t: -95, tn: 88, sn: 88, tf: 88, sf: 88, an: 0, fn: -80, af: 170, ff: 20 }, { t: -110, tn: 70, sn: 70, tf: 70, sf: 70, an: 0, fn: -80, af: 170, ff: 20 }], hold: [700, 1700] } },
  { id: 'birddog', name: 'Bird dog', cat: 'Core', eq: ['mat'], type: 'hold', uni: true, joints: { back: 0, hip: 0, knee: 1, shoulder: 1 }, lvl: 1,
    why: 'Trains the back and hip muscles to hold the spine steady while the arms and legs move. Big 3.',
    setup: 'Hands under shoulders, knees under hips, spine neutral (neither arched nor rounded).',
    steps: ['Brace lightly.', 'Reach one arm forward and the opposite leg back until both are level with the torso.', 'Make a fist and squeeze; hold about 10 seconds.', 'Return with control, sweep the hand and knee along the floor, and reach again. Switch sides.'],
    cues: ['Balance a glass of water on your low back', 'Push the heel back, not up', 'Hips stay level'],
    faults: ['Arching the low back as the leg lifts', 'Hips rotating open', 'Lifting the leg too high'],
    jointNote: 'Knees: use a folded mat under the knees. Wrists or shoulders: go onto fists or reduce the reach.',
    fig: { frames: [{ t: 75, tn: 0, sn: -90, tf: 0, sf: -90, an: 0, fn: 0, af: 0, ff: 0, fN: -90, fF: -90 }, { t: 82, tn: 0, sn: -90, fN: -90, tf: -88, sf: -88, fF: 0, an: 96, fn: 96, af: 0, ff: 0 }], hold: [700, 1700] } },
  { id: 'deadbug', name: 'Dead bug', cat: 'Core', eq: ['mat'], type: 'reps', uni: true, joints: { back: 0, hip: 0, knee: 0, shoulder: 0 }, lvl: 1, reps: [6, 10],
    why: 'Anti-extension core control: arms and legs move while the low back stays quiet.',
    setup: 'On your back, arms straight up, hips and knees bent 90 degrees.',
    steps: ['Exhale and gently press the low back toward the floor.', 'Slowly lower one arm overhead and the opposite leg toward the floor.', 'Stop before the back starts to lift. Return and switch.'],
    cues: ['Slow: 3 seconds out, 3 back', 'Ribs down', 'Exhale as the limbs lower'],
    faults: ['Low back arching off the floor', 'Rushing', 'Holding the breath'],
    jointNote: 'Back: shorten the range if the low back lifts. Shoulders: reach only as far overhead as is comfortable.',
    fig: { frames: [{ t: -90, tn: 180, sn: 90, tf: 180, sf: 90, fN: 180, fF: 180, an: 180, fn: 180, af: 180, ff: 180 }, { t: -90, tn: 180, sn: 90, fN: 180, tf: 100, sf: 100, fF: 190, an: -80, fn: -85, af: 180, ff: 180 }], hold: [500, 700], anchor: 'hip' } },
  { id: 'plank', name: 'Front plank', cat: 'Core', eq: ['mat'], type: 'hold', uni: false, joints: { back: 1, hip: 0, knee: 0, shoulder: 1 }, lvl: 1, secs: [20, 40],
    why: 'Whole-body bracing. Useful as a finisher; the Big 3 do most of the back work.',
    setup: 'Forearms on the floor, elbows under shoulders, legs straight on the toes.',
    steps: ['Squeeze glutes and quads.', 'Brace and hold a straight line from ears to heels.', 'Breathe; stop the set when form slips.'],
    cues: ['Pull the elbows toward the toes (without moving them)', 'Long neck', 'Tuck the tailbone slightly'],
    faults: ['Sagging hips', 'Butt high', 'Holding the breath'],
    jointNote: 'Back: sagging puts load on the low back. Shorter, cleaner holds beat long, sloppy ones.',
    fig: { frames: [{ t: 104, tn: -76, sn: -76, tf: -76, sf: -76, an: 0, fn: 90, af: 0, ff: 90 }] } },
  { id: 'pallof', name: 'Pallof press', cat: 'Core', eq: ['band'], type: 'reps', uni: true, joints: { back: 0, hip: 0, knee: 0, shoulder: 1 }, lvl: 1, reps: [8, 12],
    why: 'Anti-rotation: teaches the trunk to resist twisting, the way it must when you carry, row or run.',
    setup: 'Anchor a band at chest height. Stand side-on to the anchor, feet hip-width, holding the band at your chest with both hands.',
    steps: ['Brace and press the hands straight out from the chest.', 'Hold 2 seconds, resisting the pull toward the anchor.', 'Bring the hands back to the chest. Finish the reps, then face the other way.'],
    cues: ['Hands stay centered on your breastbone line', 'Ribs down, glutes on', 'Step farther from the anchor to make it harder'],
    faults: ['Twisting toward the anchor', 'Leaning away', 'Shrugging'],
    jointNote: 'Shoulders: keep the elbows soft and the shoulder blades down.',
    fig: { frames: [{ an: 20, fn: 165, af: 20, ff: 165 }, { an: 88, fn: 90, af: 88, ff: 90 }], hold: [500, 1600], props: [{ k: 'band', x: -38, y: -52 }] } },
  { id: 'suitcase', name: 'Suitcase carry', cat: 'Carry', eq: ['dumbbells'], type: 'carry', uni: true, joints: { back: 1, hip: 1, knee: 0, shoulder: 1 }, lvl: 1, inc: 5, dist: [30, 40],
    why: 'One-sided carry. The side core has to stop you leaning, which directly protects the back when you carry gear.',
    setup: 'One dumbbell in one hand, standing tall.',
    steps: ['Brace, shoulders level, eyes forward.', 'Walk with short, controlled steps for the set distance.', 'Switch hands and walk back.'],
    cues: ['Stand tall, as if a string pulls up from the crown', 'Shoulders level; the weight never touches the leg', 'Slow and quiet steps'],
    faults: ['Leaning toward or away from the weight', 'Shrugging the loaded shoulder', 'Rushing'],
    jointNote: 'Back: go lighter before you lean. Grip usually fails first; that is fine.',
    fig: { frames: [{ tn: 18, sn: 2, tf: -16, sf: -30, an: 0, fn: 0, af: -18, ff: 5 }, { tn: -16, sn: -30, tf: 18, sf: 2, an: 0, fn: 0, af: 14, ff: 30 }], hold: [0, 0], move: 520, props: [{ k: 'db', side: 'N' }] } },
  { id: 'farmer', name: 'Farmer carry', cat: 'Carry', eq: ['dumbbells'], type: 'carry', uni: false, joints: { back: 1, hip: 1, knee: 0, shoulder: 1 }, lvl: 1, inc: 5, dist: [30, 40],
    why: 'Two-handed loaded walk. Builds grip, posture and trunk stiffness for hikes with a pack.',
    setup: 'A dumbbell in each hand, standing tall.',
    steps: ['Brace, shoulders down and back.', 'Walk with controlled steps for the set distance.', 'Set the weights down with a hip hinge, not a round back.'],
    cues: ['Tall posture', 'Short, quick steps', 'Breathe behind the brace'],
    faults: ['Leaning forward', 'Rounding to pick up or put down', 'Shrugging'],
    jointNote: 'Back: pick up and set down with a hinge. Knees and hips: steady steps, no shuffling.',
    fig: { frames: [{ tn: 18, sn: 2, tf: -16, sf: -30, an: 0, fn: 0, af: 0, ff: 0 }, { tn: -16, sn: -30, tf: 18, sf: 2, an: 0, fn: 0, af: 0, ff: 0 }], hold: [0, 0], move: 520, props: [{ k: 'db' }] } },

  /* ---------- Hinge ---------- */
  { id: 'dowelhinge', name: 'Hip hinge with dowel', cat: 'Hinge', eq: ['dowel or broomstick'], type: 'reps', uni: false, joints: { back: 1, hip: 1, knee: 0, shoulder: 0 }, lvl: 1, reps: [8, 12], next: 'rdl',
    why: 'The key skill for protecting the back: bend at the hips, not the spine. Master it before loading.',
    setup: 'Hold a dowel along your spine, one hand behind the neck and one at the low back. The dowel touches head, upper back and tailbone.',
    steps: ['Soften the knees.', 'Push the hips straight back while the chest tips forward.', 'Keep all three contact points on the dowel.', 'Stop when you feel the hamstrings stretch; drive the hips forward to stand.'],
    cues: ['Close a car door with your butt', 'Shins stay nearly vertical', 'The dowel never leaves the tailbone'],
    faults: ['Head or tailbone losing contact (spine bending)', 'Squatting down instead of hips back', 'Overarching at the top'],
    jointNote: 'Back: this pattern is the rehab. Loaded gradually, it trains the back for lifting and hiking.',
    fig: { frames: [{ t: 180, an: -150, fn: 60, af: -30, ff: 60 }, { t: 118, tn: 14, sn: -4, tf: 14, sf: -4, an: 148, fn: -2, af: -92, ff: -2 }], hold: [600, 900], props: [{ k: 'dowel' }] } },
  { id: 'rdl', name: 'Dumbbell Romanian deadlift', cat: 'Hinge', eq: ['dumbbells'], type: 'reps', uni: false, joints: { back: 2, hip: 1, knee: 0, shoulder: 0 }, lvl: 2, reps: [6, 10], inc: 5, prev: 'dowelhinge', next: 'bstance_rdl',
    why: 'The loaded hinge. The most transferable strength exercise for lifting, hiking and back resilience.',
    setup: 'Stand with feet hip-width, a dumbbell in each hand in front of the thighs.',
    steps: ['Brace and soften the knees.', 'Push the hips back, sliding the weights down the thighs.', 'Stop when the hamstrings are stretched or the back wants to round, usually mid-shin.', 'Drive the hips forward to stand tall; squeeze the glutes.'],
    cues: ['Weights close to the legs', 'Proud chest, long neck', 'Hips back, not down'],
    faults: ['Rounding the low back to reach lower', 'Weights drifting forward', 'Leaning back at the top'],
    jointNote: 'Back: range is set by keeping the spine neutral, not by touching the floor. Twinge next morning = keep load the same next time.',
    fig: { frames: [{ t: 180, an: 2, fn: 2, af: 2, ff: 2 }, { t: 118, tn: 14, sn: -4, tf: 14, sf: -4, an: -2, fn: -2, af: -2, ff: -2 }], hold: [500, 700], props: [{ k: 'db' }] } },
  { id: 'bstance_rdl', name: 'B-stance Romanian deadlift', cat: 'Hinge', eq: ['dumbbells'], type: 'reps', uni: true, joints: { back: 2, hip: 1, knee: 0, shoulder: 0 }, lvl: 2, reps: [6, 10], inc: 5, prev: 'rdl', next: 'slrdl',
    why: 'Most weight on the front leg, the back foot only for balance. A bridge to single-leg work that trail running needs.',
    setup: 'Front foot flat; back foot a half-step behind with only the toes down. Dumbbells in both hands.',
    steps: ['Load about 80% onto the front leg.', 'Hinge back as in the RDL.', 'Stand by driving the front hip forward.', 'Finish the reps and switch legs.'],
    cues: ['Hips square to the front', 'Back toes are a kickstand', 'Neutral spine'],
    faults: ['Hips rotating open', 'Pushing through the back foot', 'Rounding'],
    jointNote: 'Hips: keep both hip points level.',
    fig: { frames: [{ t: 180, tf: -8, sf: -18, fF: 45, an: 2, fn: 2, af: 2, ff: 2 }, { t: 118, tn: 14, sn: -4, tf: -2, sf: -24, fF: 40, an: -2, fn: -2, af: -2, ff: -2 }], hold: [500, 700], props: [{ k: 'db' }] } },
  { id: 'slrdl', name: 'Single-leg Romanian deadlift', cat: 'Hinge', eq: ['dumbbells'], type: 'reps', uni: true, joints: { back: 1, hip: 2, knee: 1, shoulder: 0 }, lvl: 3, reps: [6, 10], inc: 5, prev: 'bstance_rdl',
    why: 'Single-leg hip strength and balance for uneven trails. Protects hips and knees by training control.',
    setup: 'Stand on one leg, dumbbell in the opposite hand. A wall within reach helps at first.',
    steps: ['Hinge forward while the free leg reaches straight back.', 'Keep the body one straight line from head to back heel.', 'Stop when the torso is near horizontal or balance gets shaky.', 'Return to standing with the glute of the standing leg.'],
    cues: ['Body tips like a seesaw', 'Back toes point down, hips square', 'Soft standing knee'],
    faults: ['Opening the hip (toes turn out)', 'Rounding the back to reach', 'Locked standing knee'],
    jointNote: 'Knee: keep the standing knee soft and tracking over the second toe.',
    fig: { frames: [{ t: 180, tf: -6, sf: -26, an: 2, fn: 2, af: 2, ff: 2 }, { t: 100, tn: 12, sn: -6, tf: -80, sf: -80, fF: 5, an: -4, fn: -4, af: -4, ff: -4 }], hold: [500, 800], props: [{ k: 'db', side: 'N' }] } },
  { id: 'glutebridge', name: 'Glute bridge', cat: 'Glutes', eq: ['mat'], type: 'reps', uni: false, joints: { back: 0, hip: 1, knee: 0, shoulder: 0 }, lvl: 1, reps: [10, 15], next: 'slbridge',
    why: 'Wakes up the glutes, which share the load the low back would otherwise take.',
    setup: 'On your back, knees bent, feet flat and hip-width, arms on the floor.',
    steps: ['Brace and push through the heels.', 'Lift the hips until shoulders, hips and knees line up.', 'Squeeze the glutes 2 seconds.', 'Lower slowly.'],
    cues: ['Ribs down; lift with the hips, not by arching', 'Push the knees slightly out', 'Feel it in the glutes, not the hamstrings or back'],
    faults: ['Arching the low back at the top', 'Knees collapsing inward', 'Hamstrings cramping (move the feet closer)'],
    jointNote: 'Back: stop at a straight line; going higher only arches the spine.',
    fig: { frames: [{ t: -90, tn: 135, sn: 40, tf: 135, sf: 40, fN: 90, fF: 90, an: 90, fn: 90, af: 90, ff: 90 }, { t: -70, tn: 110, sn: 30, tf: 110, sf: 30, fN: 90, fF: 90, an: 105, fn: 95, af: 105, ff: 95 }], hold: [500, 1400] } },
  { id: 'slbridge', name: 'Single-leg glute bridge', cat: 'Glutes', eq: ['mat'], type: 'reps', uni: true, joints: { back: 0, hip: 1, knee: 0, shoulder: 0 }, lvl: 1, reps: [8, 12], prev: 'glutebridge', next: 'hipthrust',
    why: 'One-sided glute strength; finds and fixes left-right differences.',
    setup: 'As the glute bridge, but one knee pulled toward the chest or the leg held straight.',
    steps: ['Push through the heel of the working foot.', 'Lift until the hips are level and in line.', 'Hold 2 seconds; lower slowly.', 'Finish the reps, then switch.'],
    cues: ['Hips stay level, no tilting', 'Heel drives down', 'Ribs down'],
    faults: ['One hip dropping', 'Arching the back', 'Pushing with the shoulders'],
    jointNote: 'Hips: level pelvis is the whole point.',
    fig: { frames: [{ t: -90, tn: 135, sn: 40, fN: 90, tf: 170, sf: 100, an: 90, fn: 90, af: 90, ff: 90 }, { t: -70, tn: 110, sn: 30, fN: 90, tf: 110, sf: 110, an: 105, fn: 95, af: 105, ff: 95 }], hold: [500, 1400] } },
  { id: 'hipthrust', name: 'Dumbbell hip thrust (bench)', cat: 'Glutes', eq: ['bench', 'dumbbells'], type: 'reps', uni: false, joints: { back: 1, hip: 1, knee: 0, shoulder: 0 }, lvl: 2, reps: [8, 12], inc: 5, prev: 'slbridge',
    why: 'Loads the glutes heavily with little stress on the spine.',
    setup: 'Upper back against the long side of the bench, feet flat, a dumbbell across the hips (a folded towel helps).',
    steps: ['Tuck the chin and brace.', 'Drive through the heels until the thighs and torso are level.', 'Squeeze 1 to 2 seconds at the top.', 'Lower under control.'],
    cues: ['Shins vertical at the top', 'Eyes follow the torso, looking forward', 'Finish with glutes, not the low back'],
    faults: ['Overarching at the top', 'Feet too far forward (hamstrings take over)', 'Bench sliding'],
    jointNote: 'Back: rib cage stays down. Place the bench against a wall.',
    fig: { frames: [{ t: -120, tn: 120, sn: 20, tf: 120, sf: 20, fN: 90, fF: 90, an: 60, fn: 60, af: 60, ff: 60, pin: { j: 'neck', x: -31, y: -21 } }, { t: -90, tn: 90, sn: 0, tf: 90, sf: 0, fN: 90, fF: 90, an: 90, fn: 90, af: 90, ff: 90, pin: { j: 'neck', x: -31, y: -21 } }], hold: [500, 1300], props: [{ k: 'bench', x: -62, y: -19, w: 34 }, { k: 'dbhip' }] } },

  /* ---------- Squat and single-leg ---------- */
  { id: 'boxsquat', name: 'Goblet squat to box', cat: 'Squat', eq: ['dumbbells', 'bench'], type: 'reps', uni: false, joints: { back: 1, hip: 1, knee: 1, shoulder: 0 }, lvl: 1, reps: [8, 12], inc: 5, next: 'gobletsquat',
    why: 'Squat pattern with a depth target. The box teaches you to sit back and controls knee stress.',
    setup: 'Stand in front of the bench, feet shoulder-width, toes slightly out, holding one dumbbell vertically at the chest.',
    steps: ['Brace.', 'Sit back and down until you lightly touch the bench.', 'Keep tension; do not relax onto it.', 'Stand by pushing the floor away.'],
    cues: ['Knees track over the toes', 'Chest tall, elbows inside the knees', 'Whole foot on the floor'],
    faults: ['Plopping onto the box', 'Knees caving in', 'Heels lifting'],
    jointNote: 'Knees: a higher box = less knee bend. Raise the box if knees ache; lower it over weeks.',
    fig: { frames: [{ t: 180, an: 25, fn: 165, af: 25, ff: 165 }, { t: 145, tn: 82, sn: -24, tf: 82, sf: -24, an: 40, fn: 175, af: 40, ff: 175 }], hold: [500, 800], props: [{ k: 'kb' }, { k: 'box', x: -30, y: -21, w: 24 }] } },
  { id: 'gobletsquat', name: 'Goblet squat', cat: 'Squat', eq: ['dumbbells'], type: 'reps', uni: false, joints: { back: 1, hip: 1, knee: 1, shoulder: 0 }, lvl: 2, reps: [8, 12], inc: 5, prev: 'boxsquat',
    why: 'The front-loaded squat keeps the torso upright and the back safe while building legs for hills.',
    setup: 'Feet shoulder-width, toes slightly out, dumbbell held vertically at the chest.',
    steps: ['Brace.', 'Sit down between the heels as deep as you can with a neutral spine.', 'Pause 1 second.', 'Stand up by pushing the floor away.'],
    cues: ['Elbows brush the inside of the knees', 'Knees follow the toes', 'Tall chest'],
    faults: ['Tailbone tucking under at the bottom', 'Knees collapsing', 'Rising hips-first'],
    jointNote: 'Hips: if the hip pinches at the bottom, widen the stance and turn the toes out a bit more.',
    fig: { frames: [{ t: 180, an: 25, fn: 165, af: 25, ff: 165 }, { t: 150, tn: 95, sn: -32, tf: 95, sf: -32, an: 40, fn: 175, af: 40, ff: 175 }], hold: [500, 800], props: [{ k: 'kb' }] } },
  { id: 'stepup', name: 'Step-up', cat: 'Single leg', eq: ['bench', 'dumbbells'], type: 'reps', uni: true, joints: { back: 0, hip: 1, knee: 1, shoulder: 0 }, lvl: 1, reps: [8, 12], inc: 5, next: 'splitsquat',
    why: 'Direct transfer to climbing trails and stairs. Builds each leg separately.',
    setup: 'Face a sturdy box or bench. Start with a height that puts the thigh a little below level.',
    steps: ['Plant the whole foot on the box.', 'Lean slightly forward and drive through that heel to stand up tall.', 'Lower slowly on the same leg, touching the floor softly.', 'Finish the reps, then switch.'],
    cues: ['Knee tracks over the middle toes', 'Push, do not hop from the back foot', 'Control the way down: 3 seconds'],
    faults: ['Pushing off the bottom foot', 'Knee caving in', 'Dropping down'],
    jointNote: 'Knees: lower the box if the knee aches. The slow lowering is what strengthens knee control.',
    fig: { frames: [{ t: 172, tn: 68, sn: -11, an: 6, fn: 6, af: -6, ff: -2, pin: { j: 'ankleF', x: 0, y: 0 } }, { t: 180, tn: 0, sn: 0, tf: -6, sf: -26, an: 2, fn: 2, af: 2, ff: 2, pin: { j: 'ankleN', x: 18, y: -15 } }], hold: [500, 700], props: [{ k: 'box', x: 8, y: -15, w: 26 }] } },
  { id: 'splitsquat', name: 'Split squat', cat: 'Single leg', eq: ['dumbbells'], type: 'reps', uni: true, joints: { back: 0, hip: 1, knee: 1, shoulder: 0 }, lvl: 2, reps: [8, 12], inc: 5, prev: 'stepup', next: 'reverselunge',
    why: 'Static lunge. Builds single-leg strength and hip-flexor length on the back leg.',
    setup: 'Long split stance, back heel up, feet hip-width apart (on train tracks, not a tightrope).',
    steps: ['Brace, torso tall.', 'Lower straight down until the back knee is just above the floor.', 'Drive up through the front foot.', 'Finish the reps, then switch.'],
    cues: ['Straight down, like an elevator', 'Front shin can tilt forward a little', 'Squeeze the back-leg glute'],
    faults: ['Stance too narrow (wobbling)', 'Leaning way forward', 'Back knee slamming down'],
    jointNote: 'Knees: a longer stance shifts load to the hip; a shorter one to the knee. Pick what feels good.',
    fig: { frames: [{ t: 180, tn: 22, sn: 4, tf: -24, sf: -24, fF: 50, an: 2, fn: 2, af: 2, ff: 2 }, { t: 178, tn: 80, sn: -8, tf: -12, sf: -85, fF: 0, an: 2, fn: 2, af: 2, ff: 2 }], hold: [500, 700], props: [{ k: 'db' }] } },
  { id: 'reverselunge', name: 'Reverse lunge', cat: 'Single leg', eq: ['dumbbells'], type: 'reps', uni: true, joints: { back: 0, hip: 1, knee: 1, shoulder: 0 }, lvl: 2, reps: [8, 12], inc: 5, prev: 'splitsquat', next: 'rfess',
    why: 'Stepping back is easier on the knees than stepping forward, and trains control for downhill running.',
    setup: 'Stand tall, feet hip-width, dumbbells at the sides.',
    steps: ['Step one foot back and lower until the back knee is just off the floor.', 'Front knee over the middle of the foot.', 'Drive through the front foot to return to standing.', 'Alternate or finish one side first.'],
    cues: ['Long step back', 'Torso tall or a slight lean', 'Quiet back knee'],
    faults: ['Short step (knee shoots forward)', 'Wobbling side to side', 'Pushing off the back foot'],
    jointNote: 'Knees: the most knee-friendly lunge. Go bodyweight if the front knee complains.',
    fig: { frames: [{ t: 180, an: 2, fn: 2, af: 2, ff: 2 }, { t: 176, tn: 80, sn: -8, tf: -12, sf: -85, fF: 0, an: 2, fn: 2, af: 2, ff: 2, anchor: 'ankleN' }], hold: [500, 700], props: [{ k: 'db' }] } },
  { id: 'rfess', name: 'Rear-foot-elevated split squat', cat: 'Single leg', eq: ['bench', 'dumbbells'], type: 'reps', uni: true, joints: { back: 0, hip: 1, knee: 2, shoulder: 0 }, lvl: 3, reps: [6, 10], inc: 5, prev: 'reverselunge',
    why: 'The Bulgarian split squat: the strongest single-leg builder you can do at home.',
    setup: 'Back foot laces-down on the bench, front foot far enough forward that the front shin can stay near vertical.',
    steps: ['Brace, slight forward lean.', 'Lower until the front thigh is about level.', 'Drive up through the whole front foot.', 'Finish the reps, then switch.'],
    cues: ['Most weight on the front foot', 'Knee over the toes', 'Control the bottom'],
    faults: ['Front foot too close (knee pain)', 'Bouncing', 'Twisting'],
    jointNote: 'Knees: hardest on the front knee. Drop back to reverse lunges on flagged-knee days.',
    fig: { frames: [{ t: 176, tn: 18, sn: 2, tf: -40, sf: 30, fF: -20, an: 2, fn: 2, af: 2, ff: 2 }, { t: 168, tn: 82, sn: -10, tf: -5, sf: -60, fF: -40, an: 2, fn: 2, af: 2, ff: 2 }], hold: [500, 800], props: [{ k: 'db' }, { k: 'bench', x: -52, y: -19, w: 22 }] } },
  { id: 'stepdown', name: 'Slow step-down', cat: 'Knee care', eq: ['bench'], type: 'reps', uni: true, joints: { back: 0, hip: 1, knee: 1, shoulder: 0 }, lvl: 1, reps: [6, 10],
    why: 'Eccentric knee control, the ability that protects knees on descents.',
    setup: 'Stand on a low step (4 to 8 inches) on one leg, the other foot hanging off the front.',
    steps: ['Bend the standing knee to lower the free heel toward the floor over 3 to 4 seconds.', 'Touch the heel lightly; do not shift weight to it.', 'Stand back up.', 'Finish the reps, then switch.'],
    cues: ['Knee tracks over the second toe', 'Hips level', 'Slow is the exercise'],
    faults: ['Knee diving inward', 'Hip dropping on the free side', 'Dropping fast'],
    jointNote: 'Knees: a mirror helps; the knee must not cave inward. Start with a very low step.',
    fig: { frames: [{ t: 180, tn: 0, sn: 0, tf: 20, sf: 12, an: 30, fn: 50, af: 30, ff: 50, pin: { j: 'ankleN', x: 0, y: -12 } }, { t: 165, tn: 50, sn: -30, tf: 30, sf: 0, an: 40, fn: 70, af: 40, ff: 70, pin: { j: 'ankleN', x: 0, y: -12 } }], hold: [500, 1600], move: 1800, props: [{ k: 'box', x: -9, y: -12, w: 16 }] } },
  { id: 'spanish', name: 'Spanish squat (band)', cat: 'Knee care', eq: ['band'], type: 'hold', uni: false, joints: { back: 0, hip: 0, knee: 1, shoulder: 0 }, lvl: 1, secs: [30, 45],
    why: 'Loads the quads and patellar tendon while the band holds the shins upright. Well tolerated by sore knees.',
    setup: 'Loop a heavy band around a fixed post and behind both knees. Step back until it is taut.',
    steps: ['Sit back into the band, shins vertical, torso upright.', 'Lower to a comfortable depth, up to thighs level.', 'Hold 30 to 45 seconds.', 'Stand, rest, repeat.'],
    cues: ['Lean into the band', 'Shins stay vertical', 'Weight in the heels'],
    faults: ['Knees drifting forward', 'Leaning the torso way forward', 'Too little band tension'],
    jointNote: 'Knees: a common rehab choice for sore knees. Mild discomfort that settles by the next morning is acceptable; sharp pain is not.',
    fig: { frames: [{ t: 180, an: 30, fn: 90, af: 30, ff: 90 }, { t: 168, tn: 80, sn: 0, tf: 80, sf: 0, an: 70, fn: 90, af: 70, ff: 90 }], hold: [500, 1800], props: [{ k: 'band', from: 'knee', x: 42, y: -18 }] } },
  { id: 'tke', name: 'Terminal knee extension (band)', cat: 'Knee care', eq: ['band'], type: 'reps', uni: true, joints: { back: 0, hip: 0, knee: 0, shoulder: 0 }, lvl: 1, reps: [12, 20],
    why: 'Strengthens the last few degrees of knee straightening. Easy on the joint, good on bad-knee days.',
    setup: 'Band anchored low in front of you and looped behind one knee. Step back to tension.',
    steps: ['Let the band pull the knee slightly bent.', 'Straighten the knee fully by squeezing the quad.', 'Hold 2 seconds; release slowly.', 'Finish the reps, then switch.'],
    cues: ['Heel stays down', 'Squeeze the thigh hard at the end', 'Slow return'],
    faults: ['Hips swinging instead of knee straightening', 'Locking the knee with a snap'],
    jointNote: 'Knees: pain-free by design. Useful as a warm-up before squats.',
    fig: { frames: [{ t: 178, tn: 18, sn: -8, an: 5, fn: 5, af: 5, ff: 5 }, { t: 180, tn: 2, sn: 0, an: 5, fn: 5, af: 5, ff: 5 }], hold: [400, 1200], props: [{ k: 'band', from: 'knee', x: 40, y: -10 }] } },
  { id: 'calfraise', name: 'Single-leg calf raise', cat: 'Knee care', eq: ['bench'], type: 'reps', uni: true, joints: { back: 0, hip: 0, knee: 0, shoulder: 0 }, lvl: 1, reps: [12, 20],
    why: 'Calf and Achilles capacity is the first line of defense for runners\' knees, shins and feet.',
    setup: 'Stand on one foot, ball of the foot on a step, a hand on the wall for balance.',
    steps: ['Rise as high as you can.', 'Pause 1 second.', 'Lower over 3 seconds below the step.', 'Finish the reps, then switch.'],
    cues: ['Straight up, over the big toe', 'Full range', 'Slow down'],
    faults: ['Bouncing', 'Rolling to the outside of the foot', 'Short range'],
    jointNote: 'A common screen: 20 or more good single-leg raises per side before running volume goes up.',
    fig: { frames: [{ t: 180, tf: 12, sf: 30, an: 95, fn: 85, af: 95, ff: 85, fN: 110 }, { t: 180, tf: 12, sf: 30, an: 95, fn: 85, af: 95, ff: 85, fN: 150 }], hold: [400, 800], props: [{ k: 'wall', x: 31, top: -80 }] } },
  { id: 'tibraise', name: 'Tibialis raise', cat: 'Knee care', eq: [], type: 'reps', uni: false, joints: { back: 0, hip: 0, knee: 0, shoulder: 0 }, lvl: 1, reps: [15, 25],
    why: 'Strengthens the front of the shin. Helps with shin splints and downhill running.',
    setup: 'Lean your back against a wall, heels a foot or so out from it.',
    steps: ['Pull the toes up toward the shins as high as possible.', 'Pause, lower slowly.', 'Repeat. Walk the feet farther out to make it harder.'],
    cues: ['Knees straight', 'Full range', 'Burn is normal'],
    faults: ['Bending the knees', 'Bouncing'],
    jointNote: 'Knees and shins: good for downhill trail running.',
    fig: { frames: [{ t: 190, tn: 10, sn: 10, tf: 10, sf: 10, an: 5, fn: 5, af: 5, ff: 5 }, { t: 190, tn: 10, sn: 10, tf: 10, sf: 10, fN: 60, fF: 60, an: 5, fn: 5, af: 5, ff: 5 }], hold: [400, 700], props: [{ k: 'wall', x: -17, top: -80 }] } },

  /* ---------- Hip care ---------- */
  { id: 'sidelyingabd', name: 'Side-lying hip abduction', cat: 'Hip care', eq: ['mat'], type: 'reps', uni: true, joints: { back: 0, hip: 1, knee: 0, shoulder: 0 }, lvl: 1, reps: [12, 20], next: 'lateralwalk',
    why: 'Strengthens the glute medius, which keeps the pelvis level and the knee from caving when you run.',
    setup: 'Lie on your side, bottom knee bent, top leg straight in line with the body.',
    steps: ['Turn the top toes slightly down.', 'Lift the leg to about 30 to 40 degrees, heel leading.', 'Lower slowly.', 'Finish the reps, then switch.'],
    cues: ['Leg slightly behind the body line', 'Do not roll backward', 'Lead with the heel'],
    faults: ['Leg drifting forward (hip flexors take over)', 'Hiking the hip toward the ribs', 'Swinging'],
    jointNote: 'Hips: a burn on the outside of the hip is the right muscle.',
    fig: { frames: [{ t: -90, tn: 90, sn: 90, tf: 90, sf: 90, an: -180, fn: -90, af: 90, ff: 90 }, { t: -90, tn: 90, sn: 90, tf: 122, sf: 122, an: -180, fn: -90, af: 90, ff: 90 }], hold: [400, 1000], anchor: 'hip' } },
  { id: 'lateralwalk', name: 'Banded lateral walk', cat: 'Hip care', eq: ['band'], type: 'reps', uni: true, joints: { back: 0, hip: 1, knee: 0, shoulder: 0 }, lvl: 1, reps: [10, 15], prev: 'sidelyingabd', next: 'copenhagen_short',
    why: 'Hip stabilizer strength in a standing, athletic position. (Shown from the front.)',
    setup: 'Mini-band around the lower thighs or ankles. Quarter-squat, feet hip-width.',
    steps: ['Step sideways with the lead foot, keeping tension.', 'Follow with the trail foot, never letting the feet touch.', 'Take the reps one way, then come back.'],
    cues: ['Stay low and level', 'Toes forward', 'Push the knees out against the band'],
    faults: ['Bobbing up and down', 'Knees caving', 'Leaning the torso'],
    jointNote: 'Hips and knees: trains the muscles that keep the knee lined up over the foot.',
    fig: { frames: [{ t: 172, tn: 12, sn: -4, tf: -12, sf: 4, fN: 90, fF: -90, an: 20, fn: 90, af: -20, ff: -90 }, { t: 172, tn: 26, sn: -10, tf: -8, sf: 8, fN: 90, fF: -90, an: 20, fn: 90, af: -20, ff: -90 }], hold: [300, 600] } },
  { id: 'copenhagen_short', name: 'Copenhagen plank, short lever', cat: 'Hip care', eq: ['bench', 'mat'], type: 'hold', uni: true, joints: { back: 0, hip: 1, knee: 1, shoulder: 1 }, lvl: 2, secs: [15, 30], prev: 'lateralwalk', next: 'copenhagen',
    why: 'Inner-thigh (adductor) strength. In a large trial with soccer players, a Copenhagen program cut groin problems substantially.',
    setup: 'Side plank on the forearm with the top knee resting on the bench; bottom leg hangs underneath.',
    steps: ['Press the top knee into the bench and lift the hips into a straight line.', 'Hold 15 to 30 seconds.', 'Lower, then switch sides.'],
    cues: ['Straight body line', 'Squeeze the top knee down into the bench', 'Breathe'],
    faults: ['Hips sagging', 'Twisting'],
    jointNote: 'Knee: padding under the knee. Hips: start with short holds; adductors get sore easily.',
    fig: { frames: [{ t: -117, tn: 130, sn: 90, tf: 100, sf: 95, an: 0, fn: -90, af: 170, ff: 20, pin: { j: 'kneeN', x: 30, y: -19 } }, { t: -90, tn: 90, sn: 90, tf: 60, sf: 10, an: 0, fn: -90, af: 170, ff: 20, pin: { j: 'kneeN', x: 30, y: -19 } }], hold: [600, 1800], props: [{ k: 'bench', x: 24, y: -17, w: 30 }] } },
  { id: 'copenhagen', name: 'Copenhagen plank, long lever', cat: 'Hip care', eq: ['bench', 'mat'], type: 'hold', uni: true, joints: { back: 0, hip: 2, knee: 1, shoulder: 1 }, lvl: 3, secs: [15, 30], prev: 'copenhagen_short',
    why: 'Harder adductor version: top ankle on the bench.',
    setup: 'Side plank on the forearm, top foot or ankle on the bench.',
    steps: ['Lift the hips into a straight line, bottom leg hanging or lifted to the bench.', 'Hold 15 to 30 seconds.', 'Switch sides.'],
    cues: ['Straight line from head to top foot', 'Press down through the top leg'],
    faults: ['Sagging', 'Holding too long too soon'],
    jointNote: 'Hips: adductor soreness can last 2 days; progress slowly.',
    fig: { frames: [{ t: -90, tn: 90, sn: 90, tf: 40, sf: 20, an: 0, fn: -90, af: 170, ff: 20, pin: { j: 'ankleN', x: 46, y: -19 } }], props: [{ k: 'bench', x: 38, y: -17, w: 24 }] } },

  /* ---------- Push ---------- */
  { id: 'inclinepushup', name: 'Incline push-up (hands on bench)', cat: 'Push', eq: ['bench'], type: 'reps', uni: false, joints: { back: 0, hip: 0, knee: 0, shoulder: 1 }, lvl: 1, reps: [8, 15], next: 'pushup',
    why: 'Push-up pattern at a lower load. Push-ups let the shoulder blades move freely, which shoulders like.',
    setup: 'Hands on the bench edge, a bit wider than shoulders; body straight from head to heels.',
    steps: ['Brace and squeeze glutes.', 'Lower the chest to the bench, elbows about 45 degrees from the body.', 'Push the bench away until the arms are straight and the upper back is slightly rounded.'],
    cues: ['Body moves as one plank', 'Elbows angled back, not flared', 'Finish by spreading the shoulder blades'],
    faults: ['Hips sagging', 'Elbows flared straight out', 'Head poking forward'],
    jointNote: 'Shoulders: the 45-degree elbow angle is kinder than flared elbows.',
    fig: { frames: [{ t: 132, tn: -48, sn: -48, tf: -48, sf: -48, an: 0, fn: 0, af: 0, ff: 0, fN: -48 + 90, pin: { j: 'wriN', x: 55, y: -17.5 } }, { t: 121, tn: -59, sn: -59, tf: -59, sf: -59, an: -65, fn: 20, af: -65, ff: 20, pin: { j: 'wriN', x: 55, y: -17.5 } }], hold: [400, 600], props: [{ k: 'bench', x: 44, y: -15, w: 28 }] } },
  { id: 'pushup', name: 'Push-up', cat: 'Push', eq: ['mat'], type: 'reps', uni: false, joints: { back: 1, hip: 0, knee: 0, shoulder: 1 }, lvl: 1, reps: [6, 15], prev: 'inclinepushup', next: 'dbbench',
    why: 'Upper-body pushing plus a moving plank.',
    setup: 'Hands a bit wider than shoulders, body straight on the toes.',
    steps: ['Brace.', 'Lower until the chest is a fist from the floor, elbows about 45 degrees.', 'Push up to straight arms and a slightly rounded upper back.'],
    cues: ['Screw the hands into the floor (elbows back)', 'Plank body', 'Full range'],
    faults: ['Sagging hips', 'Half reps', 'Elbows flared'],
    jointNote: 'Shoulders and wrists: push-up handles or fists can ease the wrists.',
    fig: { frames: [{ t: 116, tn: -64, sn: -64, tf: -64, sf: -64, an: 0, fn: 0, af: 0, ff: 0, pin: { j: 'wriN', x: 60, y: 0 } }, { t: 104, tn: -76, sn: -76, tf: -76, sf: -76, an: -68, fn: 18, af: -68, ff: 18, pin: { j: 'wriN', x: 60, y: 0 } }], hold: [400, 600] } },
  { id: 'dbbench', name: 'Dumbbell bench press', cat: 'Push', eq: ['bench', 'dumbbells'], type: 'reps', uni: false, joints: { back: 0, hip: 0, knee: 0, shoulder: 2 }, lvl: 1, reps: [6, 12], inc: 5, prev: 'pushup',
    why: 'Loaded pushing on the bench. Dumbbells let each shoulder find its own path.',
    setup: 'Lie on the bench, feet flat, shoulder blades pulled back and down, dumbbells over the chest.',
    steps: ['Lower the dumbbells to the sides of the chest, elbows about 45 degrees.', 'Pause lightly.', 'Press up and slightly in.'],
    cues: ['Shoulder blades pinned to the bench', 'Forearms vertical', 'Feet planted'],
    faults: ['Elbows flared to 90 degrees', 'Bouncing at the bottom', 'Butt lifting'],
    jointNote: 'Shoulders: on flagged-shoulder days use a neutral grip (palms facing) and stop an inch higher.',
    fig: { frames: [{ t: -90, tn: 90, sn: 0, tf: 90, sf: 0, fN: 90, fF: 90, an: 180, fn: 180, af: 180, ff: 180, pin: { j: 'hip', x: 0, y: -21 } }, { t: -90, tn: 90, sn: 0, tf: 90, sf: 0, fN: 90, fF: 90, an: 125, fn: 180, af: 125, ff: 180, pin: { j: 'hip', x: 0, y: -21 } }], hold: [400, 600], props: [{ k: 'bench', x: -36, y: -19, w: 44 }, { k: 'db' }] } },
  { id: 'hkpress', name: 'Half-kneeling one-arm dumbbell press', cat: 'Push', eq: ['dumbbells', 'mat'], type: 'reps', uni: true, joints: { back: 1, hip: 0, knee: 1, shoulder: 2 }, lvl: 1, reps: [8, 12], inc: 5,
    why: 'Overhead pressing with the ribs and pelvis locked in place, which protects the low back from arching.',
    setup: 'Half-kneeling, the pressing arm on the same side as the down knee. Dumbbell at the shoulder, palm facing in.',
    steps: ['Squeeze the glute of the down leg and brace.', 'Press up and slightly forward until the arm is straight by the ear.', 'Lower to the shoulder under control.'],
    cues: ['Ribs down, no leaning back', 'Palm can rotate forward as you press', 'Biceps finishes by the ear'],
    faults: ['Arching the low back', 'Shrugging hard', 'Pressing out in front'],
    jointNote: 'Shoulders: use the range that is pain-free; a landmine-style angled press is the fallback on bad days.',
    fig: { frames: [{ t: 180, tn: 90, sn: 0, tf: -5, sf: -90, fF: 0, an: 20, fn: 175, af: 5, ff: 5 }, { t: 180, tn: 90, sn: 0, tf: -5, sf: -90, fF: 0, an: 172, fn: 175, af: 5, ff: 5 }], hold: [400, 600], props: [{ k: 'db', side: 'N' }] } },
  { id: 'pushupplus', name: 'Push-up plus', cat: 'Shoulder care', eq: ['mat'], type: 'reps', uni: false, joints: { back: 0, hip: 0, knee: 0, shoulder: 0 }, lvl: 1, reps: [10, 15],
    why: 'Trains the serratus, the muscle that keeps the shoulder blade tight to the ribs. Key for healthy shoulders.',
    setup: 'Top of a push-up, or on the knees or against a wall to start.',
    steps: ['Keep arms straight.', 'Let the chest sink between the shoulder blades.', 'Then push the floor away, spreading the shoulder blades as far as they go.', 'Hold 1 second.'],
    cues: ['Arms stay locked; only the shoulder blades move', 'Push the floor away'],
    faults: ['Bending the elbows', 'Sagging hips'],
    jointNote: 'Shoulders: a staple of shoulder rehab programs.',
    fig: { frames: [{ t: 113, tn: -67, sn: -67, tf: -67, sf: -67, an: 0, fn: 0, af: 0, ff: 0, c: 0 }, { t: 117, tn: -63, sn: -63, tf: -63, sf: -63, an: 0, fn: 0, af: 0, ff: 0, c: -2.5 }], hold: [400, 800] } },

  /* ---------- Pull ---------- */
  { id: 'bandrow', name: 'Band row', cat: 'Pull', eq: ['band'], type: 'reps', uni: false, joints: { back: 0, hip: 0, knee: 0, shoulder: 0 }, lvl: 1, reps: [12, 20], next: 'dbrow',
    why: 'Horizontal pull with no load on the spine. Balances all the pushing and sitting.',
    setup: 'Band anchored at chest height. Stand tall facing it, arms straight in front.',
    steps: ['Pull the shoulder blades back first.', 'Then pull the elbows back past the ribs.', 'Squeeze 1 second; return slowly.'],
    cues: ['Shoulders down away from the ears', 'Elbows close to the body', 'Chest stays still'],
    faults: ['Shrugging', 'Leaning back', 'Jerking'],
    jointNote: 'Shoulders: pain-free for most people; good daily filler.',
    fig: { frames: [{ t: 180, an: 88, fn: 88, af: 88, ff: 88 }, { t: 180, an: -32, fn: 85, af: -32, ff: 85 }], hold: [400, 900], props: [{ k: 'band', x: 58, y: -56 }] } },
  { id: 'dbrow', name: 'One-arm dumbbell row (bench)', cat: 'Pull', eq: ['bench', 'dumbbells'], type: 'reps', uni: true, joints: { back: 1, hip: 0, knee: 0, shoulder: 1 }, lvl: 1, reps: [8, 12], inc: 5, prev: 'bandrow',
    why: 'The main upper-back builder. The bench supports the spine so the back stays neutral.',
    setup: 'One hand and the same-side knee on the bench, the other foot on the floor. Back flat. Dumbbell hanging under the shoulder.',
    steps: ['Brace, back flat as a table.', 'Pull the elbow up and back toward the hip.', 'Squeeze the shoulder blade; lower until the arm is straight.'],
    cues: ['Elbow to hip pocket', 'No twisting of the torso', 'Long neck'],
    faults: ['Twisting to lift more', 'Shrugging', 'Rounded back'],
    jointNote: 'Back: the bench support makes this back-friendly. Shoulders: stop short of the shoulder rolling forward at the bottom.',
    fig: { frames: [{ t: 95, tn: 0, sn: -90, fN: -90, tf: -5, sf: -5, an: 0, fn: 0, af: 0, ff: 0, pin: { j: 'kneeN', x: 0, y: -19 } }, { t: 95, tn: 0, sn: -90, fN: -90, tf: -5, sf: -5, an: -55, fn: 5, af: 0, ff: 0, pin: { j: 'kneeN', x: 0, y: -19 } }], hold: [400, 800], props: [{ k: 'bench', x: -26, y: -17, w: 62 }, { k: 'db', side: 'N' }] } },
  { id: 'bandpulldown', name: 'Band straight-arm pulldown', cat: 'Pull', eq: ['band'], type: 'reps', uni: false, joints: { back: 0, hip: 0, knee: 0, shoulder: 1 }, lvl: 1, reps: [12, 20],
    why: 'Trains the lats, the big back muscles that also help stiffen the low back.',
    setup: 'Band anchored high (top of a door). Step back, slight hinge, arms straight overhead holding the band.',
    steps: ['Keep arms nearly straight.', 'Sweep the hands down to the thighs.', 'Squeeze the lats; return slowly.'],
    cues: ['Ribs down', 'Shoulders away from the ears', 'Arc, not a pull'],
    faults: ['Bending the elbows into a row', 'Arching the back'],
    jointNote: 'Shoulders: stop the top of the range where the shoulder feels open, not pinched.',
    fig: { frames: [{ t: 165, tn: 5, sn: 0, tf: 5, sf: 0, an: 150, fn: 150, af: 150, ff: 150 }, { t: 165, tn: 5, sn: 0, tf: 5, sf: 0, an: 5, fn: 5, af: 5, ff: 5 }], hold: [400, 800], props: [{ k: 'band', x: 58, y: -92 }] } },
  { id: 'facepull', name: 'Band face pull', cat: 'Shoulder care', eq: ['band'], type: 'reps', uni: false, joints: { back: 0, hip: 0, knee: 0, shoulder: 0 }, lvl: 1, reps: [12, 20],
    why: 'Rear shoulders and rotator cuff. Counteracts rounded shoulders and protects the shoulder joint.',
    setup: 'Band anchored at face height. Palms down or thumbs back.',
    steps: ['Pull the band toward the forehead, elbows high.', 'Finish with the hands beside the ears, knuckles back.', 'Return slowly.'],
    cues: ['Elbows high and wide', 'Rotate the hands back at the end', 'Chin tucked'],
    faults: ['Leaning back', 'Shrugging', 'Elbows dropping'],
    jointNote: 'Shoulders: light and high reps. It should feel easy on the joint.',
    fig: { frames: [{ t: 180, an: 100, fn: 100, af: 100, ff: 100 }, { t: 180, an: 95, fn: -170, af: 95, ff: -170 }], hold: [400, 900], props: [{ k: 'band', x: 58, y: -70 }] } },
  { id: 'pullapart', name: 'Band pull-apart', cat: 'Shoulder care', eq: ['band'], type: 'reps', uni: false, joints: { back: 0, hip: 0, knee: 0, shoulder: 0 }, lvl: 1, reps: [15, 25],
    why: 'Upper-back and rear-shoulder endurance for posture.',
    setup: 'Hold a light band in front of the chest, arms straight, hands shoulder-width.',
    steps: ['Pull the band apart until it touches the chest.', 'Squeeze the shoulder blades together.', 'Return slowly.'],
    cues: ['Arms straight', 'Shoulders down', 'Squeeze and hold 1 second'],
    faults: ['Arching the back', 'Shrugging'],
    jointNote: 'Shoulders: use a band light enough to do 20 easy reps.',
    fig: { frames: [{ t: 180, an: 88, fn: 88, af: 88, ff: 88 }, { t: 180, an: 88, fn: 88, af: -85, ff: -85 }], hold: [400, 900] } },
  { id: 'extrot', name: 'Band external rotation', cat: 'Shoulder care', eq: ['band'], type: 'reps', uni: true, joints: { back: 0, hip: 0, knee: 0, shoulder: 0 }, lvl: 1, reps: [12, 20],
    why: 'Rotator cuff strength. The small muscles that keep the shoulder ball centered in the socket.',
    setup: 'Band anchored at elbow height, standing side-on. Elbow bent 90 degrees and pinned to the side (a rolled towel under the arm helps).',
    steps: ['Rotate the forearm outward, away from the belly, keeping the elbow at the side.', 'Pause, return slowly.', 'Finish the reps, then turn around for the other arm.'],
    cues: ['Elbow glued to the ribs', 'Slow on the way back', 'Wrist straight'],
    faults: ['Elbow drifting away from the body', 'Twisting the torso'],
    jointNote: 'Shoulders: light load, many reps. This should never hurt.', },
  { id: 'wallslide', name: 'Wall slide', cat: 'Shoulder care', eq: [], type: 'reps', uni: false, joints: { back: 0, hip: 0, knee: 0, shoulder: 0 }, lvl: 1, reps: [8, 12],
    why: 'Overhead shoulder mobility with good shoulder-blade motion. Also a quick test of overhead range.',
    setup: 'Forearms on the wall in front of you, elbows at shoulder height, a light band around the wrists optional.',
    steps: ['Slide the forearms up the wall while the shoulder blades rotate up.', 'Lift the hands off the wall at the top for a second.', 'Slide back down.'],
    cues: ['Ribs down', 'Shoulders away from the ears at the top', 'Slow'],
    faults: ['Arching the back to get higher', 'Shrugging'],
    jointNote: 'Shoulders: go only as high as stays pain-free.',
    fig: { frames: [{ t: 180, an: 95, fn: 180, af: 95, ff: 180 }, { t: 180, an: 165, fn: 175, af: 165, ff: 175 }], hold: [400, 900], props: [{ k: 'wall', x: 20, top: -100 }] } },

  /* ---------- Mobility ---------- */
  { id: 'catcamel', name: 'Cat-camel', cat: 'Mobility', eq: ['mat'], type: 'reps', uni: false, joints: { back: 0, hip: 0, knee: 1, shoulder: 0 }, lvl: 1, reps: [6, 10],
    why: 'Gentle spine motion to reduce stiffness before training. McGill\'s standard warm-up. It is motion, not a stretch.',
    setup: 'Hands and knees.',
    steps: ['Slowly round the back up, head down.', 'Slowly let it sag and look up.', 'Move through the middle range; do not push the ends.'],
    cues: ['Slow cycles', 'Move, do not stretch hard', '5 to 8 cycles is enough'],
    faults: ['Forcing end range', 'Going fast'],
    jointNote: 'Back: this is a lubricating motion, not a flexibility drill.',
    fig: { frames: [{ t: 75, tn: 0, sn: -90, tf: 0, sf: -90, fN: -90, fF: -90, an: 0, fn: 0, af: 0, ff: 0, c: 4, h: -40 }, { t: 75, tn: 0, sn: -90, tf: 0, sf: -90, fN: -90, fF: -90, an: 0, fn: 0, af: 0, ff: 0, c: -5, h: 30 }], hold: [500, 500], move: 1500 } },
  { id: 'hipflexor', name: 'Half-kneeling hip-flexor stretch', cat: 'Mobility', eq: ['mat'], type: 'hold', uni: true, joints: { back: 0, hip: 0, knee: 1, shoulder: 0 }, lvl: 1, secs: [30, 45],
    why: 'Tight hip flexors pull on the low back and limit stride. Sitting and running both tighten them.',
    setup: 'Half-kneeling, back knee on a pad, front foot flat.',
    steps: ['Tuck the tailbone under and squeeze the back-leg glute.', 'Shift forward slightly until you feel the front of the back hip stretch.', 'Reach the same-side arm overhead for more.', 'Hold 30 to 45 seconds; switch.'],
    cues: ['Tuck first, then shift', 'Tall torso', 'Small movement, big stretch'],
    faults: ['Arching the low back', 'Lunging far forward without the tuck'],
    jointNote: 'Back: the pelvic tuck protects the low back and aims the stretch at the hip.',
    fig: { frames: [{ t: 180, tn: 90, sn: 0, tf: -4, sf: -90, fF: 0, an: 5, fn: 5, af: 5, ff: 5 }, { t: 183, tn: 70, sn: -20, tf: -26, sf: -90, fF: 0, an: 172, fn: 175, af: 5, ff: 5 }], hold: [500, 1800] } },
  { id: 'hamband', name: 'Supine hamstring stretch (band)', cat: 'Mobility', eq: ['band'], type: 'hold', uni: true, joints: { back: 0, hip: 0, knee: 0, shoulder: 0 }, lvl: 1, secs: [30, 45],
    why: 'Hamstring length without bending the spine forward.',
    setup: 'On your back, a band or towel around one foot, the other leg straight on the floor.',
    steps: ['Raise the banded leg with the knee straight until you feel a stretch.', 'Hold 30 to 45 seconds, breathing.', 'Switch.'],
    cues: ['Low back stays on the floor', 'Bottom leg stays straight', 'Mild stretch only'],
    faults: ['Bending the knee to get higher', 'Bottom leg lifting'],
    jointNote: 'Back: safer than standing toe-touch stretches for a sensitive back.',
    fig: { frames: [{ t: -90, tn: 90, sn: 90, tf: 130, sf: 130, an: 140, fn: 150, af: 140, ff: 150 }, { t: -90, tn: 90, sn: 90, tf: 165, sf: 165, an: 160, fn: 170, af: 160, ff: 170 }], hold: [500, 1800], anchor: 'hip' } },
  { id: 'ninety90', name: '90/90 hip switches', cat: 'Mobility', eq: ['mat'], type: 'reps', uni: false, joints: { back: 0, hip: 1, knee: 1, shoulder: 0 }, lvl: 1, reps: [6, 10],
    why: 'Hip internal and external rotation, which runners and people who sit a lot usually lose.',
    setup: 'Sit on the floor, knees bent 90 degrees, feet wider than hips, hands behind you if needed.',
    steps: ['Let both knees fall to one side (front leg and back leg both at 90 degrees).', 'Sit tall.', 'Rotate both knees to the other side.', 'Move slowly through a comfortable range.'],
    cues: ['Tall spine', 'Use your hands behind you at first', 'Range grows over weeks'],
    faults: ['Forcing the knees to the floor', 'Slouching'],
    jointNote: 'Knees: if the back knee complains, keep the feet wider and the range smaller.' },
  { id: 'openbook', name: 'Side-lying open book', cat: 'Mobility', eq: ['mat'], type: 'reps', uni: true, joints: { back: 0, hip: 0, knee: 0, shoulder: 0 }, lvl: 1, reps: [6, 10],
    why: 'Upper-back (thoracic) rotation. A mobile upper back spares the low back and the shoulders.',
    setup: 'Lie on your side, hips and knees bent 90 degrees, arms straight in front together. A pillow under the head.',
    steps: ['Keep the knees stacked and together.', 'Open the top arm up and over, following it with the eyes, turning the chest to the ceiling.', 'Pause, breathe out, return.'],
    cues: ['Knees stay glued together', 'Rotate from the ribs', 'Breathe out at the end range'],
    faults: ['Knees coming apart (twisting the low back)', 'Forcing the arm to the floor'],
    jointNote: 'Back: the knees stay put so rotation comes from the upper back.' },
  { id: 'kneetowall', name: 'Knee-to-wall ankle mobilization', cat: 'Mobility', eq: [], type: 'reps', uni: true, joints: { back: 0, hip: 0, knee: 0, shoulder: 0 }, lvl: 1, reps: [10, 15],
    why: 'Ankle bend (dorsiflexion). Stiff ankles push stress up into the knees and hips.',
    setup: 'Half-kneeling facing a wall, front toes a few inches from the wall.',
    steps: ['Drive the front knee forward to touch the wall, heel down.', 'Return.', 'Move the foot back as it gets easy. Measure the distance for your assessment.'],
    cues: ['Heel stays down', 'Knee goes over the middle toes'],
    faults: ['Heel lifting', 'Knee caving inward'],
    jointNote: 'Knees: often relieves knee pain in squats and on descents.',
    fig: { frames: [{ t: 180, tn: 90, sn: 0, tf: -4, sf: -90, fF: 0, an: 30, fn: 90, af: 5, ff: 5 }, { t: 180, tn: 68, sn: -26, tf: -24, sf: -90, fF: 0, an: 45, fn: 95, af: 5, ff: 5 }], hold: [400, 800], props: [{ k: 'wall', x: 16, top: -60 }] } },
  { id: 'wgs', name: 'World\'s greatest stretch', cat: 'Mobility', eq: [], type: 'reps', uni: true, joints: { back: 0, hip: 1, knee: 1, shoulder: 0 }, lvl: 1, reps: [4, 6],
    why: 'Hip flexors, hamstrings, groin and upper-back rotation in one flowing drill. A good pre-run warm-up.',
    setup: 'Step into a long lunge with the back knee down or up.',
    steps: ['Place the hand on the same side as the back leg on the floor.', 'Drop the other elbow toward the front instep.', 'Rotate that arm to the ceiling, eyes following.', 'Return, straighten the front leg to stretch the hamstring, then switch.'],
    cues: ['Long lunge', 'Breathe out into each position', 'Slow'],
    faults: ['Rushing', 'Rounding hard'],
    jointNote: 'Knees: back knee down on a pad if kneeling is hard.',
    fig: { frames: [{ t: 130, tn: 80, sn: -5, tf: -60, sf: -80, fF: 20, an: 20, fn: 20, af: 0, ff: 0 }, { t: 130, tn: 80, sn: -5, tf: -60, sf: -80, fF: 20, an: -175, fn: -175, af: 0, ff: 0 }], hold: [600, 1200] } },
  { id: 'doorpec', name: 'Doorway chest stretch', cat: 'Mobility', eq: [], type: 'hold', uni: true, joints: { back: 0, hip: 0, knee: 0, shoulder: 1 }, lvl: 1, secs: [30, 45],
    why: 'Opens the chest and front of the shoulder, countering rounded posture.',
    setup: 'Forearm on a door frame, elbow at or below shoulder height.',
    steps: ['Step through gently until you feel the chest stretch.', 'Hold 30 to 45 seconds; switch.'],
    cues: ['Elbow at or below shoulder height', 'Gentle; no pinching in the front of the shoulder'],
    faults: ['Elbow too high (shoulder pinch)', 'Leaning hard'],
    jointNote: 'Shoulders: stop if you feel pinching rather than a stretch.' },
  { id: 'calfstretch', name: 'Wall calf stretch', cat: 'Mobility', eq: [], type: 'hold', uni: true, joints: { back: 0, hip: 0, knee: 0, shoulder: 0 }, lvl: 1, secs: [30, 45],
    why: 'Calf and Achilles length after running.',
    setup: 'Hands on a wall, one leg back with the heel down.',
    steps: ['Straight back knee: hold 30 seconds.', 'Bend the back knee slightly: hold 30 seconds for the lower calf.', 'Switch.'],
    cues: ['Back heel down', 'Toes forward'],
    faults: ['Heel lifting', 'Foot turned out'],
    jointNote: 'Knees and ankles: helpful after long or hilly runs.',
    fig: { frames: [{ t: 160, tn: 20, sn: 0, tf: -22, sf: -22, fF: 90, an: 110, fn: 100, af: 110, ff: 100 }, { t: 160, tn: 25, sn: -5, tf: -18, sf: -35, fF: 90, an: 110, fn: 100, af: 110, ff: 100 }], hold: [600, 1400], props: [{ k: 'wall', x: 36, top: -90 }] } },

  /* ---------- Cardio ---------- */
  { id: 'row', name: 'Rowing machine', cat: 'Cardio', eq: ['rower'], type: 'time', uni: false, joints: { back: 1, hip: 1, knee: 1, shoulder: 0 }, lvl: 2,
    why: 'Full-body, zero-impact cardio. Good for intervals when legs or joints need a break from running.',
    setup: 'Feet strapped across the balls of the feet. Damper 3 to 5 (higher is not better).',
    steps: ['Catch: shins vertical, arms straight, torso leaning slightly forward from the hips.', 'Drive: legs push first, then the torso swings back slightly, then the arms pull to the lower ribs.', 'Recovery: arms out, torso forward from the hips, then knees bend.', 'Legs 60%, body 20%, arms 20%.'],
    cues: ['Legs, body, arms; arms, body, legs', 'Hinge at the hips; never round to reach', 'Recovery about twice as long as the drive'],
    faults: ['Rounding the low back at the catch', 'Pulling with the arms first', 'Damper cranked to 10'],
    jointNote: 'Back: the rounded catch is how rowers hurt their backs. Hinge forward, keep a neutral spine, and shorten the reach if needed.',
    fig: { frames: [{ t: 160, tn: 140, sn: 20, tf: 140, sf: 20, fN: 60, fF: 60, an: 90, fn: 90, af: 90, ff: 90, pin: { j: 'hip', x: 0, y: -12 } }, { t: 198, tn: 86, sn: 86, tf: 86, sf: 86, fN: 176, fF: 176, an: -30, fn: 80, af: -30, ff: 80, pin: { j: 'hip', x: -23.5, y: -12 } }], hold: [150, 350], move: 800, props: [{ k: 'rail', x1: -40, x2: 26, y: -6 }] } },
  { id: 'run', name: 'Running (road or treadmill)', cat: 'Cardio', eq: [], type: 'time', uni: false, joints: { back: 1, hip: 1, knee: 2, shoulder: 0 }, lvl: 4,
    why: 'Running builds aerobic fitness quickly and burns the most energy per minute.',
    setup: 'Easy runs at conversational pace: you can speak in full sentences.',
    steps: ['Warm up with 5 minutes of walking.', 'Run tall with a slight forward lean from the ankles.', 'Quick, light steps (about 165 to 180 per minute), landing under the hips.'],
    cues: ['Run quietly', 'Relaxed shoulders and hands', 'If you cannot talk, slow down'],
    faults: ['Overstriding (heel far in front)', 'Too fast on easy days', 'Big jumps in session length'],
    jointNote: 'Knees and hips: a slightly quicker cadence reduces load at the knee. Avoid any single run much longer than your longest recent run.',
    fig: { frames: [{ t: 172, tn: 40, sn: -10, tf: -20, sf: -60, an: -40, fn: 60, af: 30, ff: 110 }, { t: 172, tn: -20, sn: -60, tf: 40, sf: -10, an: 30, fn: 110, af: -40, ff: 60 }], hold: [0, 0], move: 340 } },
  { id: 'walk', name: 'Brisk walk or incline treadmill', cat: 'Cardio', eq: [], type: 'time', uni: false, joints: { back: 0, hip: 0, knee: 0, shoulder: 0 }, lvl: 1,
    why: 'The base of back health and of fat loss. Incline walking reaches Zone 2 with little impact.',
    setup: 'Treadmill incline 6 to 12%, or hills outside.',
    steps: ['Walk briskly, arms swinging.', 'Stay tall; do not hold the treadmill rails.'],
    cues: ['Brisk but conversational', 'Tall posture'],
    faults: ['Holding the rails (it cancels the work)', 'Leaning forward'],
    jointNote: 'Back: daily walking is part of every back rehab phase.',
    fig: { frames: [{ tn: 18, sn: 2, tf: -16, sf: -30, an: -16, fn: 0, af: 16, ff: 30 }, { tn: -16, sn: -30, tf: 18, sf: 2, an: 16, fn: 30, af: -16, ff: 0 }], hold: [0, 0], move: 560 } },
];
const EXM = Object.fromEntries(EX.map((e) => [e.id, e]));

/* Progression chains: the app picks the current step for each slot. */
const CHAINS = {
  hinge: ['dowelhinge', 'rdl', 'bstance_rdl', 'slrdl'],
  bridge: ['glutebridge', 'slbridge', 'hipthrust'],
  squat: ['boxsquat', 'gobletsquat'],
  single: ['stepup', 'splitsquat', 'reverselunge', 'rfess'],
  knee: ['tke', 'spanish', 'stepdown'],
  hipcare: ['sidelyingabd', 'lateralwalk', 'copenhagen_short', 'copenhagen'],
  pushH: ['inclinepushup', 'pushup', 'dbbench'],
  pushV: ['hkpress'],
  pullH: ['bandrow', 'dbrow'],
  pullV: ['bandpulldown'],
  cuff: ['extrot', 'facepull', 'pullapart'],
  serratus: ['pushupplus', 'wallslide'],
  carry: ['suitcase', 'farmer'],
  antirot: ['pallof', 'deadbug'],
  calf: ['calfraise', 'tibraise'],
};
/* Friendlier swaps when a joint is flagged in the morning check-in. */
const SWAPS = {
  knee: { rfess: 'reverselunge', reverselunge: 'stepup', splitsquat: 'stepup', gobletsquat: 'boxsquat', stepup: 'spanish', stepdown: 'tke', boxsquat: 'glutebridge', copenhagen: 'sidelyingabd', copenhagen_short: 'sidelyingabd' },
  hip: { slrdl: 'rdl', rfess: 'splitsquat', gobletsquat: 'boxsquat', copenhagen: 'sidelyingabd', copenhagen_short: 'sidelyingabd' },
  shoulder: { dbbench: 'pushup', hkpress: 'pushupplus', pushup: 'inclinepushup', bandpulldown: 'pullapart', dbrow: 'bandrow' },
  back: { rdl: 'dowelhinge', bstance_rdl: 'dowelhinge', slrdl: 'glutebridge', gobletsquat: 'boxsquat', farmer: 'pallof', suitcase: 'pallof', hipthrust: 'glutebridge', pushup: 'inclinepushup', plank: 'deadbug' },
};

/* Session templates. slot entries: [slot or exercise id, sets, repsLow, repsHigh | secs] */
const TEMPLATES = {
  lowerA: { name: 'Strength A: hinge and hips', kind: 'strength', mins: 40, big3: true,
    items: [['hinge', 3, 6, 10], ['bridge', 3, 8, 12], ['single', 2, 8, 12], ['hipcare', 2, 12, 15], ['carry', 3, 30, 40]] },
  upperB: { name: 'Strength B: upper body and shoulders', kind: 'strength', mins: 40, big3: true,
    items: [['pushH', 3, 6, 12], ['pullH', 3, 8, 12], ['pushV', 2, 8, 12], ['pullV', 2, 12, 20], ['cuff', 2, 12, 20], ['antirot', 2, 8, 12]] },
  lowerC: { name: 'Strength C: squat and knees', kind: 'strength', mins: 40, big3: true,
    items: [['squat', 3, 8, 12], ['knee', 2, 8, 12], ['hinge', 2, 8, 10], ['calf', 2, 12, 20], ['serratus', 2, 10, 15], ['carry', 2, 30, 40]] },
  easy: { name: 'Easy aerobic (Zone 2)', kind: 'cardio', mins: 35, cardio: 'z2' },
  intervals: { name: 'Intervals (4x4)', kind: 'cardio', mins: 35, cardio: 'intervals' },
  long: { name: 'Long run, trail run or hike', kind: 'cardio', mins: 50, cardio: 'long' },
  mobility: { name: 'Recovery: mobility and walk', kind: 'mobility', mins: 25,
    items: [['catcamel', 1, 6, 8], ['hipflexor', 1, 30, 45], ['hamband', 1, 30, 45], ['ninety90', 1, 6, 8], ['openbook', 1, 6, 8], ['kneetowall', 1, 10, 12], ['wallslide', 1, 8, 10], ['calfstretch', 1, 30, 30]] },
  rest: { name: 'Rest day', kind: 'rest', mins: 0 },
};
const DAILY10 = ['catcamel', 'hipflexor', 'ninety90', 'openbook', 'kneetowall', 'wallslide'];
const DEFAULT_WEEK = ['mobility', 'lowerA', 'easy', 'upperB', 'intervals', 'lowerC', 'long']; // Sun..Sat

/* Walk-run ladder for back level 3 (return to run). Each stage: repeats x [run sec, walk sec]. */
const RUN_LADDER = [
  { reps: 8, run: 60, walk: 90 }, { reps: 8, run: 90, walk: 90 }, { reps: 7, run: 120, walk: 60 }, { reps: 6, run: 180, walk: 60 },
  { reps: 5, run: 240, walk: 60 }, { reps: 4, run: 360, walk: 60 }, { reps: 3, run: 480, walk: 60 }, { reps: 2, run: 720, walk: 60 },
  { reps: 1, run: 1500, walk: 0 },
];

const BACK_LEVELS = [
  null,
  { name: 'Level 1: Foundation', desc: 'Daily walks, Big 3, bridges, hinge practice without load. No running.' },
  { name: 'Level 2: Build strength', desc: 'Light loaded hinge, squat and carries. Incline walking and easy rowing for cardio.' },
  { name: 'Level 3: Load and return to impact', desc: 'Heavier posterior-chain and single-leg work. Walk-run intervals once the return-to-run checklist passes.' },
  { name: 'Level 4: Full training', desc: 'Continuous running, trail runs and intervals. Big 3 and the 24-hour rule stay in place for good.' },
];

const RTR_CHECKS = [
  'Brisk 30-minute walk with no back or leg pain during or after',
  '10 controlled single-leg squats to a chair per side, knee tracking straight',
  '20 single-leg calf raises per side',
  '30 seconds single-leg balance per side',
  '10 single-leg hops in place per side, pain-free',
  'Jog in place 60 seconds, pain-free',
  'No next-morning flare after the tests above',
];

const RED_FLAGS = [
  'Pain, numbness or tingling running down a leg',
  'Weakness in a leg or foot (tripping, foot slapping)',
  'Numbness in the groin or saddle area',
  'Any change in bladder or bowel control',
  'Back pain with fever, or after a fall',
];

const ASSESS = [
  { id: 'waist', name: 'Waist at navel', unit: 'in', better: 'down', how: 'Tape level at the navel, relaxed exhale.' },
  { id: 'rhr', name: 'Resting heart rate', unit: 'bpm', better: 'down', how: 'From Apple Watch, or 60 seconds on waking.' },
  { id: 'sp_l', name: 'Side plank hold, left', unit: 's', better: 'up', how: 'Full side plank until form breaks. McGill uses side-to-side balance: aim for left and right within 5%.' },
  { id: 'sp_r', name: 'Side plank hold, right', unit: 's', better: 'up', how: 'Same, right side.' },
  { id: 'pushups', name: 'Push-ups, max clean reps', unit: 'reps', better: 'up', how: 'Chest to a fist height, full lockout.' },
  { id: 'toetouch', name: 'Toe touch reach', unit: 'in', better: 'up', how: 'Standing, knees straight, reach slowly. Fingertips at toes = 0; past = positive; above = negative. Only if your back tolerates it.' },
  { id: 'k2w_l', name: 'Knee-to-wall, left', unit: 'in', better: 'up', how: 'Farthest toe-to-wall distance with the knee still touching and the heel down.' },
  { id: 'k2w_r', name: 'Knee-to-wall, right', unit: 'in', better: 'up', how: 'Same, right.' },
  { id: 'overhead', name: 'Wall overhead reach', unit: '0-2', better: 'up', how: 'Back against the wall, low back flat, arms straight overhead: 2 = thumbs touch the wall, 1 = within 2 inches, 0 = farther.' },
  { id: 'hipflex', name: 'Couch / Thomas test', unit: '0-2', better: 'up', how: 'Lying at the bench end, hug one knee: 2 = other thigh rests flat, 1 = thigh slightly up, 0 = thigh well up or knee straightens.' },
  { id: 'balance', name: 'Single-leg balance, eyes closed', unit: 's', better: 'up', how: 'Best of 3 per leg; record the weaker leg. Balance tends to decline with age, so it is worth tracking.' },
  { id: 'sts', name: '30-second sit-to-stand', unit: 'reps', better: 'up', how: 'Arms crossed, bench height, full stands.' },
  { id: 'row2k', name: '2,000 m row', unit: 'mm:ss', better: 'down', how: 'Damper 4 to 5, steady hard effort. Do it only at back level 3 or 4.' },
  { id: 'mile', name: '1-mile run', unit: 'mm:ss', better: 'down', how: 'Treadmill at 1% or a flat road. Level 4 only.' },
];

const GUIDES = [
  { id: 'brace', t: 'Neutral spine and the brace', b: [
    'Most back injuries come from repeated bending of the spine under load, or from load taken while the core is switched off. The fix is to move at the hips and knees while the spine stays close to its natural curves.',
    'Brace: stiffen the whole trunk as if someone were about to poke you in the belly. For daily life and most exercises about 20% effort is enough. Keep breathing behind the brace.',
    'Hinge: bend at the hips, not the waist. The dowel drill in Learn teaches it. Everything from picking up a pack to a deadlift uses it.',
    'Avoid first thing in the morning: hard forward bending and sit-ups. Discs are most hydrated then and least tolerant of bending. Do your Big 3, a walk or light work instead.'] },
  { id: 'rule24', t: 'The 24-hour rule', b: [
    'Judge a session by how your back feels the next morning, not during the session.',
    'Same or better next morning: keep progressing.',
    'Worse next morning: the next loaded session repeats the previous weights, and heavy hinging, carrying and running are swapped out for that day. Waypoint does this automatically from the morning check-in.',
    'Two "worse" mornings in 7 days: drop one back level for a week or two.',
    'Muscle soreness is fine. Sharp, pinching, or spreading back pain is not.'] },
  { id: 'redflags', t: 'Red flags: stop and get checked', b: [
    'Stop training and get prompt medical care if you notice: pain, numbness or tingling running down a leg; weakness in a leg or foot; numbness in the groin or saddle area; any change in bladder or bowel control; back pain with fever or after a fall.',
    'The groin numbness and bladder or bowel changes can signal a spinal emergency: go to an emergency room.',
    'Waypoint is fitness education, not medical advice. A physical therapist evaluation is worth one visit before heavy loading or a return to running if the back is still grumbling.'] },
  { id: 'rir', t: 'Reps in reserve (RIR)', b: [
    'After each set, rate how many more good reps you could have done: 0 = none, 1, 2, 3, or 4+.',
    'Most sets should end with 1 to 3 reps in reserve. That builds strength and muscle with a fraction of the injury risk of training to failure.',
    'Waypoint raises the weight when you hit the top of the rep range on every set with at least 1 rep in reserve and good technique. It lowers it if reps fall well short.'] },
  { id: 'new', t: 'Learning a new movement', b: [
    'Every new exercise starts in Learning mode: read the steps, watch the figure, then do one light practice set before your working sets.',
    'Rate your technique honestly after each exercise. A movement graduates from Learning after two sessions rated 4 or 5.',
    'Weight goes up only after technique is solid. Use Form check to film a set and replay it slowly next to the cues.',
    'Load comes last: pattern, then range, then control, then weight.'] },
  { id: 'zones', t: 'Zone 2 and the 4x4 intervals', b: [
    'Zone 2: easy, conversational effort. Waypoint uses 60 to 70% of estimated maximum heart rate (Tanaka: 208 minus 0.7 times age). If you can only speak a few words, slow down. Most weekly cardio should be here.',
    'Norwegian 4x4: four 4-minute hard efforts at 85 to 95% of max heart rate, each followed by 3 minutes easy. It is one of the best-studied ways to raise VO2 max, a strong predictor of healthy aging.',
    'Do intervals on the rower or an incline treadmill first; both are easier on the joints than hard running.',
    'Guideline for older adults (HHS 2018): at least 150 minutes of moderate aerobic activity a week, strength training on 2 or more days, and balance work.'] },
  { id: 'running', t: 'Running without getting hurt', b: [
    'A 2025 study of 5,205 runners (Frandsen and colleagues, British Journal of Sports Medicine) found that single runs much longer than your longest run of the past 30 days predicted injury, while weekly mileage changes did not. The study measured distance; Waypoint uses minutes because trail pace varies so much. It caps planned long runs and warns you when a logged run is more than 10% longer than your longest run of the past 30 days.',
    'Easy runs easy. Hard days hard, and few of them.',
    'Trail running: shorten the stride on descents and let the cadence rise. Downhills load the knees the most; the step-downs and split squats here build that capacity.',
    'Returning to running: the walk-run ladder in Train moves you up one stage at a time. Stay on a stage until it feels easy and passes the 24-hour rule.'] },
  { id: 'food', t: 'Losing fat while keeping muscle', b: [
    'Target: lose about 0.5% of body weight a week (Waypoint lets you pick 0.25% to 1%). Slower loss protects muscle and training quality; a 2011 trial in athletes (Garthe and colleagues) kept more lean mass at the slower rate.',
    'Protein: the default target is 1.6 grams per kilogram of goal body weight per day, split across 3 or 4 meals of 30 or more grams. The PROT-AGE group recommends at least 1.2 g/kg for active adults over 65; higher intakes help more during a calorie deficit with strength training.',
    'Daily weigh-ins are noisy (water, salt, food volume). Waypoint smooths them into a trend line; judge progress by the trend, week to week.',
    'Calorie target adapts: after two weeks of logging, Waypoint compares what you ate with how your trend weight moved and re-estimates how many calories you actually burn. The idea follows MacroFactor\'s published approach; the 3,500-calories-per-pound conversion is an approximation.'] },
];
